### 1 Celda mágica para la función encontrar pares

In [1]:
%%file encontrar_pares.c
#include <stdio.h>
int encontrar_pares(int* arr_v, int* arr_x, int* arr_y, int size, int suma){
    int i, j, total_pares;
    total_pares = 0;
    for(i=0; i < size; i++){
        for (j=i; j <size; j++){
            if (i!=j){
                if ((arr_v[i]+arr_v[j])==suma){
                    arr_x[i] = arr_v[i];
                    arr_y[i] = arr_v[j];
                    total_pares=total_pares+1;
                }
            }
        }
    }
    return total_pares;
}

Overwriting encontrar_pares.c


### Item 2

In [2]:
! gcc -c encontrar_pares.c

### Item 3

In [3]:
! gcc -shared encontrar_pares.o -o encontrar_pares.so

### Item 4

In [4]:
import numpy
import ctypes
def ctypes_encontrar_pares():
    # indicar la ruta de la shared library
    libfile = './encontrar_pares.so'

    # cargar la shared library
    lib = ctypes.CDLL(libfile)

    # tipo de dato de los argumentos
    lib.encontrar_pares.argtypes = [
        numpy.ctypeslib.ndpointer(dtype=numpy.int32),
        numpy.ctypeslib.ndpointer(dtype=numpy.int32),
        numpy.ctypeslib.ndpointer(dtype=numpy.int32),
        ctypes.c_int,
        ctypes.c_int
    ]

    lib.encontrar_pares.restype = ctypes.c_int
    
    # funcion configurada
    return lib.encontrar_pares

### Item 5

In [5]:
ctypes_encontrar_pares_raw = ctypes_encontrar_pares()

### Item 6 Prueba de funcionalidad

In [6]:
arr_v = numpy.asarray([9, 5, 4, 3, 1, 7, 2, 8]).astype(numpy.int32)
size_arr_v = arr_v.size
size_pares = ((arr_v.size)-1)*(arr_v.size)
arr_x = numpy.asarray(numpy.zeros(size_pares, dtype=numpy.int32))
arr_y = numpy.asarray(numpy.zeros(size_pares, dtype=numpy.int32))
size = arr_v.size
suma = 10

In [7]:
size_pares

56

In [8]:
ctypes_encontrar_pares_raw(arr_v, arr_x, arr_y, size, suma)

3

In [9]:
arr_x

array([9, 0, 0, 3, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [10]:
arr_y

array([1, 0, 0, 7, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [11]:
arr_v

array([9, 5, 4, 3, 1, 7, 2, 8], dtype=int32)

### Función para eliminar ceros de los arreglos x e y

In [12]:
nonzero_indexes_x = numpy.nonzero(arr_x)[0]
nonzero_indexes_y = numpy.nonzero(arr_y)[0]

In [13]:
arr_x = arr_v[nonzero_indexes_x]
arr_y = arr_v[nonzero_indexes_y]

In [14]:
arr_x

array([9, 3, 2], dtype=int32)

In [15]:
arr_y

array([9, 3, 2], dtype=int32)

### Item 7

In [16]:
def c_encontrar_pares(arr_v_n, suma_n):
    arr_x_n = numpy.asarray(numpy.zeros(size_pares, dtype=numpy.int32))
    arr_y_n = numpy.asarray(numpy.zeros(size_pares, dtype=numpy.int32))
    cant_pares = ctypes_encontrar_pares_raw(arr_v_n, arr_x_n, arr_y_n, arr_v_n.size, suma_n)
    return cant_pares

### Item 8

In [17]:
c_encontrar_pares(arr_v_n=numpy.asarray([9, 5, 4, 3, 1, 7, 2, 8]).astype(numpy.int32), suma_n=10)

3

### Item 9

In [18]:
def python_encontrar_pares(arr_v, suma):
    size = len(arr_v)
    arr_x = numpy.zeros(size, dtype=int)
    arr_y = numpy.zeros(size, dtype=int)
    total_pares = 0

    for i in range(size):
        for j in range(i+1, size):
            if (arr_v[i]+arr_v[j])==suma:
                arr_x[total_pares] = arr_v[i]
                arr_y[total_pares] = arr_v[j]
                total_pares += 1

    arr_x = arr_x[:total_pares]
    arr_y = arr_y[:total_pares]
    return arr_x, arr_y, total_pares

### Item 10 prueba de funcionalidad función python

In [19]:
x_py, y_py, total_pares = python_encontrar_pares(arr_v=numpy.asarray([9, 5, 4, 3, 1, 7, 2, 8]).astype(numpy.int32), suma=10)

### Item 11 error relativo de x

In [24]:
x_py

array([9, 3, 2])

In [21]:
y_py

array([1, 7, 8])

In [22]:
total_pares

3

In [23]:
from numpy import linalg as LA

LA.norm(x_py - arr_x)/LA.norm(x_py)

0.0

### Item 13 mediciones de tiempo

In [ ]:
import time
for i in range ()