# Laboratorio 6

* Asuma que las operaciones requieren alta precisión.
* Presente su solución con el nombre `lab6_codigoPUCP.ipynb`

In [1]:
import numpy
ns = 2**numpy.arange(5,15)

In [4]:
print(ns)

[   32    64   128   256   512  1024  2048  4096  8192 16384]


a) Implementar (en un único archivo) cuatro funciones en C que acumulen los elementos de una matriz cuadrada de números reales. Solo puede emplear un único bucle `for`. En la primera función realizar la acumulación elemento a elemento, en la segunda acumule en bloques de 2 elementos, en la tercera acumule en bloques de 4 elementos, y en la cuarta acumule en bloques de 8 elementos. (2.0 ptos)

In [32]:
%%file funciones_matrices_cuadradas.c

#include <stdio.h>
#include <stdlib.h>
#include <math.h>

int matriz_cua_1(int *arr, int N){
    int *elementos= (int *)calloc(N,sizeof(int));
    for(int i=1, i<=N, i++){
        elementos[i]= pow(arr[i],2);
    }
    return elementos;
}

int matriz_cua_2(int *arr, int N){
    int *elementos= (int *)calloc(N,sizeof(int));
    for(int i=1, i<=2, i++){
        for(int j=1, j<=N/2,j++){
            elementos[i,j]=pow(arr[j+i],2));
        }
    }
    return elementos;
}

int matriz_cua_3(int *arr, int N){
    int *elementos= (int *)calloc(N,sizeof(int));
    for(int i=a, i<=4, i++){
        for(int j=1, j<=N/4, j++){
            elementos[i,j]=pow(arr[j+i],2));
        }
    }
    return elementos;
}

int matriz_cua_4(int a, int b){
    int *elementos= (int *)calloc(N,sizeof(int));
    for(int i=1, i<=8, i++){
        for(int j=1, j<=N/8, j++){
            elementos[i,j]=pow(arr[j+i],2));
        }
    }
    return elementos;
}


Overwriting funciones_matrices_cuadradas.c


b) Coloque el comando para generar la librería dinámica del ítem (a) y genere la librería dinámica. (0.25 ptos)

In [ ]:
!gcc -shared -o funciones_matrices_cuadradas.so -fPIC funciones_matrices_cuadradas.c

c) Implemente una función que vincule la librería dinámica generada en el ítem (b) con Python usando `ctypes`. La función no recibe argumentos y debe devolver las cuatro funciones configuradas listas para su uso. (0.5 ptos)

In [ ]:
import ctypes 

funciones_matrices_cuadradas= ctypes.CDLL('/funciones_matrices_cuadradas') 

resultado1= funciones_matrices_cuadradas.matriz_cua_1(5,15)
resultado2= funciones_matrices_cuadradas.matriz_cua_2(5,15)
resultado3= funciones_matrices_cuadradas.matriz_cua_3(5,15)
resultado4= funciones_matrices_cuadradas.matriz_cua_4(5,15)

d) Haga una instancia de las cuatro funciones a partir de su función en el ítem (c) (0.25 ptos)

In [ ]:
import ctypes 
import numpy as np 
import time
import matplotlib.pyplot as plt 
import statistics 




if __name__ == '__main__':
    lib= ctypes.CDLL('/funciones_matrices_cuadradas') 
    iteraciones = 100
    lista_t1= []
    lista_t2= []
    lista_t3= []
    lista_t4= []
    N_lista = [256,512,1024,2048,4096]
    for n in N_lista:
        time1= []
        time2= []
        time3= []
        time4= []
        for _ in range(iteraciones):
            array_lista1= np.random.randint(0,10,n,dtype = np.int32)
            array_lista2= np.copy(array_lista1)
            array_lista3= np.copy(array_lista1)
            array_lista4= np.copy(array_lista1)
            t1=time.perf_counter_ns()
            res_1= funciones_matrices_cuadradas.matriz_cua_1(n,array_lista1)
            t2=time.perf_counter_ns()
            res_2= funciones_matrices_cuadradas.matriz_cua_2(n,array_lista2)
            t3=time.perf_counter_ns()
            res_3= funciones_matrices_cuadradas.matriz_cua_3(n,array_lista3)
            t4=time.perf_counter_ns()
            res_4= funciones_matrices_cuadradas.matriz_cua_4(n,array_lista4)
            t5=time.perf_counter_ns()
            time1.append(t2-t1)
            time2.append(t3-t2)
            time3.append(t4-t3)
            time4.append(t5-t4)
        lista_t1.append(statistics.median(time1))
        lista_t2.append(statistics.median(time2))
        lista_t3.append(statistics.median(time3))
        lista_t4.append(statistics.median(time4))

e) Pruebe todas sus funciones obtenidas en el ítem (d) para el menor de los valores de `ns` y la variable `Y`, y muestre que dan el mismo resultado. (0.25 ptos)

In [24]:
n = ns[0]
A = numpy.random.rand(n,n)
Y = A.flatten()

In [25]:
print(A)
print(Y)


[[0.85920401 0.46891158 0.21155254 ... 0.502207   0.13728625 0.9976528 ]
 [0.33066329 0.57413217 0.95285954 ... 0.77248359 0.9352515  0.84496301]
 [0.84689525 0.53490876 0.24750958 ... 0.01490944 0.99860709 0.56659518]
 ...
 [0.68303673 0.45003346 0.18908138 ... 0.57594644 0.46211379 0.72377787]
 [0.94701096 0.02981918 0.9054282  ... 0.42835837 0.08646911 0.13504736]
 [0.48033042 0.51432543 0.00121679 ... 0.9599913  0.03994017 0.0210801 ]]
[0.85920401 0.46891158 0.21155254 ... 0.9599913  0.03994017 0.0210801 ]


f) Pruebe todas sus funciones obtenidas en el ítem (d) para el mayor de los valores de `ns` y la variable `Y`, y muestre que dan el mismo resultado. (0.25 ptos)

In [26]:
n = ns[-1]
A = numpy.random.rand(n,n)
Y = A.flatten()

In [27]:
print(A)
print(Y)

[[0.11574593 0.20877154 0.42626391 ... 0.68689646 0.13632991 0.58855886]
 [0.5494475  0.19022897 0.25082048 ... 0.25150004 0.82069603 0.59722122]
 [0.24625584 0.1073458  0.7322252  ... 0.88837937 0.71624424 0.43014984]
 ...
 [0.20571149 0.35159392 0.4368517  ... 0.03181808 0.35220273 0.06293824]
 [0.76302541 0.54187212 0.90844894 ... 0.40254235 0.34221973 0.90371966]
 [0.19596763 0.79403193 0.18812418 ... 0.10188348 0.93373653 0.52482089]]
[0.11574593 0.20877154 0.42626391 ... 0.10188348 0.93373653 0.52482089]


g) Realice 50 mediciones de tiempo para todas sus funciones, y para todos los valores de `ns`. El valor representativo de las 20 mediciones será la mediana. (0.5 ptos)

In [ ]:
import ctypes 
import numpy as np 
import time
import matplotlib.pyplot as plt 
import statistics 




if __name__ == '__main__':
    lib= ctypes.CDLL('/funciones_matrices_cuadradas') 
    iteraciones = 50
    lista_t1= []
    lista_t2= []
    lista_t3= []
    lista_t4= []
    speedup = []
    N_lista = [256,512,1024,2048,4096]
    for n in N_lista:
        time1= []
        time2= []
        time3= []
        time4= []
        for _ in range(iteraciones):
            array_lista1= np.random.randint(0,10,n,dtype = np.int32)
            array_lista2= np.copy(array_lista1)
            array_lista3= np.copy(array_lista1)
            array_lista4= np.copy(array_lista1)
            t1=time.perf_counter_ns()
            res_1= funciones_matrices_cuadradas.matriz_cua_1(n,array_lista1)
            t2=time.perf_counter_ns()
            res_2= funciones_matrices_cuadradas.matriz_cua_2(n,array_lista2)
            t3=time.perf_counter_ns()
            res_3= funciones_matrices_cuadradas.matriz_cua_3(n,array_lista3)
            t4=time.perf_counter_ns()
            res_4= funciones_matrices_cuadradas.matriz_cua_4(n,array_lista4)
            t5=time.perf_counter_ns()
            time1.append(t2-t1)
            time2.append(t3-t2)
            time3.append(t4-t3)
            time4.append(t5-t4)
            elemento=(t5-t4)/(t2-t1)
        
        
        lista_t1.append(statistics.median(time1))
        lista_t2.append(statistics.median(time2))
        lista_t3.append(statistics.median(time3))
        lista_t4.append(statistics.median(time4))
        speedup.append(statistics.median(elemento))

h) Presente una gráfica en la que muestre como varía el tiempo de ejecución respecto del valor de `ns`. Solo para los cinco primeros valores de `ns`. (0.25 ptos)

In [ ]:
plt.plot(lista_t1[1,2,3,4,5])
plt.plot(lista_t2[1,2,3,4,5])
plt.plot(lista_t3[1,2,3,4,5])
plt.plot(lista_t4[1,2,3,4,5])

i) Presente una gráfica en la que muestre como varía el tiempo de ejecución respecto del valor de `ns`. Solo para los cinco últimos valores de `ns`. (0.25 ptos)

In [ ]:
plt.plot(lista_t1[iteraciones-4,iteraciones-3,iteraciones-2,iteraciones-1,iteraciones])
plt.plot(lista_t2[iteraciones-4,iteraciones-3,iteraciones-2,iteraciones-1,iteraciones])
plt.plot(lista_t3[iteraciones-4,iteraciones-3,iteraciones-2,iteraciones-1,iteraciones])
plt.plot(lista_t4[iteraciones-4,iteraciones-3,iteraciones-2,iteraciones-1,iteraciones])

j) Presente una gráfica en la que muestre como varía el *speedup* respecto del valor de `ns`. Solo para los cinco primeros valores de `ns`. Considere como referencia a la función más lenta. (0.25 ptos)

In [ ]:
plt.plot(speedup,lista_t4[1,2,3,4,5])

k) Presente una gráfica en la que muestre como varía el *speedup* respecto del valor de `ns`. Solo para los cinco ultimos valores de `ns`. Considere como referencia a la función más lenta. (0.25 ptos)

In [ ]:
plt.plot(speedup,lista_t4[iteraciones-4,iteraciones-3,iteraciones-2,iteraciones-1,iteraciones])

l) Implementar (en un único archivo) dos funciones en C que acumulen los elementos de una matriz cuadrada de números reales. Debe emplear dos bucle `for`. En la primera función realizar la acumulación leyendo los elementos por filas, en la segunda acumule leyendo los elementos por columnas. (1.5 ptos)

In [ ]:
%%file funciones_mat_cuadradas.c

#include <stdio.h>
#include <stlib.h>
#include <math.h>
double mat_cua_1(double *arr, double N){
    double *elementos= (double *)calloc(N,sizeof(double));
    for(int i=1, i<N, i++){
        elementos[i]= pow(arr[i+j],2);
    }
    return *elementos;
}

double mat_cua_2(double *arr, double b){
    double *elementos= (double *)calloc(N,sizeof(double));
    for(int i=1, i<=2, i++){
        for(int j=1, j<=N/2,j++){
            elementos[i,j]=pow(arr[i+j],2);
        }
    }
}

m) Coloque el comando para generar la librería dinámica del ítem (l) y genere la librería dinámica. (0.25 ptos)

In [ ]:
!gcc -shared -o funciones_mat_cuadradas.so -fPIC funciones_mat_cuadradas.c

n) Implemente una función que vincule la librería dinámica generada en el ítem (m) con Python usando `ctypes`. La función no recibe argumentos y debe devolver las dos funciones configuradas listas para su uso. (0.5 ptos)

In [ ]:
import ctypes 

funciones_mat_cuadradas= ctypes.CDLL('/funciones_mat_cuadradas') 

resultado1= funciones_mat_cuadradas.matriz_cua_1(5,15)
resultado2= funciones_mat_cuadradas.matriz_cua_2(5,15)

o) Haga una instancia de las dos funciones a partir de su función en el ítem (n) (0.25 ptos)

In [ ]:
import ctypes 
import numpy as np 
import time
import matplotlib.pyplot as plt 
import statistics 

if __name__ == '__main__':
    lib= ctypes.CDLL('/funciones_mat_cuadradas') 
    iteraciones = 100
    lista_t1= []
    lista_t2= []

    N_lista = [256,512,1024,2048,4096]
    for n in N_lista:
        time1= []
        time2= []

        for _ in range(iteraciones):
            array_lista1= np.random.randint(0,10,n,dtype = np.int64)
            array_lista2= np.copy(array_lista1)
            array_lista3= np.copy(array_lista1)
            array_lista4= np.copy(array_lista1)
            t1=time.perf_counter_ns()
            res_1= funciones_mat_cuadradas.matriz_cua_1(n,array_lista1)
            t2=time.perf_counter_ns()
            res_2= funciones_mat_cuadradas.matriz_cua_2(n,array_lista2)
            t3=time.perf_counter_ns()

            time1.append(t2-t1)
            time2.append(t3-t2)

        lista_t1.append(statistics.median(time1))
        lista_t2.append(statistics.median(time2))


p) Pruebe todas sus funciones obtenidas en el ítem (o) para el menor de los valores de `ns` y muestre que dan el mismo resultado. (0.25 ptos)

In [13]:
n = ns[0]
A = numpy.random.rand(n,n)
Y = A.flatten()

q) Pruebe todas sus funciones obtenidas en el ítem (o) para el menor de los valores de `ns` y muestre que dan el mismo resultado. (0.25 ptos)

In [ ]:
n = ns[-1]
A = numpy.random.rand(n,n)
Y = A.flatten()

r) Realice 50 mediciones de tiempo para todas sus funciones obtenidas en el ítem (o), y para todos los valores de `ns`. El valor representativo de las 20 mediciones será la mediana. (0.5 ptos)

In [ ]:
import ctypes 
import numpy as np 
import time
import matplotlib.pyplot as plt 
import statistics 

if __name__ == '__main__':
    lib= ctypes.CDLL('/funciones_mat_cuadradas') 
    iteraciones = 50
    lista_t1= []
    lista_t2= []

    N_lista = [256,512,1024,2048,4096]
    for n in N_lista:
        time1= []
        time2= []

        for _ in range(iteraciones):
            array_lista1= np.random.randint(0,10,n,dtype = np.int64)
            array_lista2= np.copy(array_lista1)
            array_lista3= np.copy(array_lista1)
            array_lista4= np.copy(array_lista1)
            t1=time.perf_counter_ns()
            res_1= funciones_mat_cuadradas.matriz_cua_1(n,array_lista1)
            t2=time.perf_counter_ns()
            res_2= funciones_mat_cuadradas.matriz_cua_2(n,array_lista2)
            t3=time.perf_counter_ns()

            time1.append(t2-t1)
            time2.append(t3-t2)

            elemento=(t3-t2)/(t2-t1)

        lista_t1.append(statistics.median(time1))
        lista_t2.append(statistics.median(time2))
        speedup.append(statistics.median(elemento))


s) Presente una gráfica en la que muestre como varía el tiempo de ejecución de las instancias del ítem (o) respecto del valor de `ns`. Solo para los cinco primeros valores de `ns`. (0.25 ptos)

In [ ]:
plt.plot(lista_t1[1,2,3,4,5])
plt.plot(lista_t2[1,2,3,4,5])

t) Presente una gráfica en la que muestre como varía el tiempo de ejecución de las instancias del ítem (o) respecto del valor de `ns`. Solo para los cinco últimos valores de `ns`. (0.25 ptos)

In [ ]:
plt.plot(lista_t1[iteraciones-4,iteraciones-3,iteraciones-2,iteraciones-1,iteraciones])
plt.plot(lista_t2[iteraciones-4,iteraciones-3,iteraciones-2,iteraciones-1,iteraciones])

u) Presente una gráfica en la que muestre como varía el *speedup* de las instancias del ítem (o) respecto del valor de `ns`. Solo para los cinco primeros valores de `ns`. Considere como referencia la función más lenta. (0.25 ptos)

In [ ]:
plt.plot(speedup,lista_t2[1,2,3,4,5])

v) Compare graficamente las implementaciones de las versiones con un solo bucle `for`, con las implementaciones de las versiones con dos bucle `for`. Presente una gráfica de tiempo de ejecución para todos los tamaños, determine cual es la más rápida y cual es la más lenta. (0.5 ptos)

In [ ]:
plt.plot(lista_t1)
plt.plot(lista_t2)

w) En base al análisis del ítem (v), presente dos gráficas de *speedup* (de la función más rápida respecto de la más lenta). Una para los primeros cinco tamaños, y otra para los cinco últimos. (0.25 ptos)

In [ ]:
plt.plot(speedup,lista_t1[1,2,3,4,5])
plt.plot(speedup,lista_t1[iteraciones-4,iteraciones-3,iteraciones-2,iteraciones-1,iteraciones])

x) Explique sus resultados de las implementaciones con un solo bucle `for` empleando conceptos de memoria caché. (2.0 ptos)

In [ ]:
#durante el uso de un solo bucle for solo se usaria una variable de iteración, esta seria de localidad espacial

y) Explique sus resultados de las implementaciones con dos bucle `for` empleando conceptos de memoria caché. (2.0 ptos)

In [ ]:
#durante el uso de dos bucles for, se usaria dos variables de iteración, por lo tanto la que está dentro de una esa de localidad temporal y la variable principal es de localidad espacial

z) ¿Qué implementación para sumar todos los elementos de una matriz es más eficiente en términos de tiempo de ejecución? ¿Por qué? Explique empleando conceptos de memoria caché. (1.0 pto)